// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AttemptErrorCode - Attempt could not complete because of an error
type AttemptErrorCode string

const (
	AttemptErrorCodeCancelled                AttemptErrorCode = "CANCELLED"
	AttemptErrorCodeTimeout                  AttemptErrorCode = "TIMEOUT"
	AttemptErrorCodeNotFound                 AttemptErrorCode = "NOT_FOUND"
	AttemptErrorCodeConnectionRefused        AttemptErrorCode = "CONNECTION_REFUSED"
	AttemptErrorCodeConnectionReset          AttemptErrorCode = "CONNECTION_RESET"
	AttemptErrorCodeMissingURL               AttemptErrorCode = "MISSING_URL"
	AttemptErrorCodeCli                      AttemptErrorCode = "CLI"
	AttemptErrorCodeCliUnavailable           AttemptErrorCode = "CLI_UNAVAILABLE"
	AttemptErrorCodeSelfSignedCert           AttemptErrorCode = "SELF_SIGNED_CERT"
	AttemptErrorCodeErrTLSCertAltnameInvalid AttemptErrorCode = "ERR_TLS_CERT_ALTNAME_INVALID"
	AttemptErrorCodeSslErrorCaUnknown        AttemptErrorCode = "SSL_ERROR_CA_UNKNOWN"
	AttemptErrorCodeTTLExpired               AttemptErrorCode = "TTL_EXPIRED"
	AttemptErrorCodeDataArchived             AttemptErrorCode = "DATA_ARCHIVED"
	AttemptErrorCodeSslCertExpired           AttemptErrorCode = "SSL_CERT_EXPIRED"
	AttemptErrorCodeBulkRetryCancelled       AttemptErrorCode = "BULK_RETRY_CANCELLED"
	AttemptErrorCodeDNSLookupFailed          AttemptErrorCode = "DNS_LOOKUP_FAILED"
	AttemptErrorCodeHostUnreachable          AttemptErrorCode = "HOST_UNREACHABLE"
	AttemptErrorCodeProtocolError            AttemptErrorCode = "PROTOCOL_ERROR"
	AttemptErrorCodeSocketClosed             AttemptErrorCode = "SOCKET_CLOSED"
	AttemptErrorCodeUnknown                  AttemptErrorCode = "UNKNOWN"
)

func (e AttemptErrorCode) ToPointer() *AttemptErrorCode {
	return &e
}

func (e *AttemptErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CANCELLED":
		fallthrough
	case "TIMEOUT":
		fallthrough
	case "NOT_FOUND":
		fallthrough
	case "CONNECTION_REFUSED":
		fallthrough
	case "CONNECTION_RESET":
		fallthrough
	case "MISSING_URL":
		fallthrough
	case "CLI":
		fallthrough
	case "CLI_UNAVAILABLE":
		fallthrough
	case "SELF_SIGNED_CERT":
		fallthrough
	case "ERR_TLS_CERT_ALTNAME_INVALID":
		fallthrough
	case "SSL_ERROR_CA_UNKNOWN":
		fallthrough
	case "TTL_EXPIRED":
		fallthrough
	case "DATA_ARCHIVED":
		fallthrough
	case "SSL_CERT_EXPIRED":
		fallthrough
	case "BULK_RETRY_CANCELLED":
		fallthrough
	case "DNS_LOOKUP_FAILED":
		fallthrough
	case "HOST_UNREACHABLE":
		fallthrough
	case "PROTOCOL_ERROR":
		fallthrough
	case "SOCKET_CLOSED":
		fallthrough
	case "UNKNOWN":
		*e = AttemptErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AttemptErrorCode: %v", v)
	}
}
